#!/usr/bin/env bash
# install.sh — Wire claude-hub into your local Claude Code setup (~/.claude)
set -euo pipefail

REPO_PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CLAUDE_DIR="$HOME/.claude"
GLOBAL_CLAUDE_MD="$CLAUDE_DIR/CLAUDE.md"
GLOBAL_SETTINGS="$CLAUDE_DIR/settings.json"

echo "=== claude-hub install ==="
echo "Repo: $REPO_PATH"
echo "Target: $CLAUDE_DIR"
echo ""

# ── 1. Generate ~/.claude/CLAUDE.md ─────────────────────────────────────────
echo "--- Generating $GLOBAL_CLAUDE_MD ---"

if [ -f "$GLOBAL_CLAUDE_MD" ] && [ ! -L "$GLOBAL_CLAUDE_MD" ]; then
  BACKUP="$GLOBAL_CLAUDE_MD.bak.$(date +%Y%m%d%H%M%S)"
  echo "  Backing up existing CLAUDE.md → $BACKUP"
  cp "$GLOBAL_CLAUDE_MD" "$BACKUP"
fi

cat > "$GLOBAL_CLAUDE_MD" << HEREDOC
# Claude Hub — Global Context

> Auto-generated by $REPO_PATH/install.sh
> Re-run install.sh after pulling updates from the repo.

@$REPO_PATH/context/engineering-principles.md
@$REPO_PATH/context/python-standards.md
@$REPO_PATH/context/typescript-standards.md
@$REPO_PATH/context/aws-conventions.md
@$REPO_PATH/context/git-conventions.md

## Skills

Before starting any task that matches a trigger below, read the full SKILL.md
first — it contains step-by-step processes, patterns, and quality gates.

| Skill | Triggers | File |
|-------|----------|------|
| \`python-refactor\` | refactor, extract, clean up, restructure Python | \`$REPO_PATH/skills/python-refactor/SKILL.md\` |
| \`write-tests\` | write tests, add tests, pytest, coverage, unit test | \`$REPO_PATH/skills/write-tests/SKILL.md\` |
| \`aws-cdk-construct\` | CDK, AWS infra, CloudFormation, stack, Fargate, Lambda | \`$REPO_PATH/skills/aws-cdk-construct/SKILL.md\` |
| \`temporal-workflow\` | Temporal, durable workflow, activity, worker | \`$REPO_PATH/skills/temporal-workflow/SKILL.md\` |
| \`mcp-server\` | MCP server, FastMCP, tool definition, benchmark MCP | \`$REPO_PATH/skills/mcp-server/SKILL.md\` |
| \`langgraph-agent\` | LangGraph, StateGraph, multi-agent, agent node | \`$REPO_PATH/skills/langgraph-agent/SKILL.md\` |
| \`eval-harness\` | eval, LLM judge, benchmark, dataset.jsonl, pass rate | \`$REPO_PATH/skills/eval-harness/SKILL.md\` |

## MCP Server Standards

- Use \`fastmcp\` (Python) for all MCP server implementations.
- Every tool must have a clear docstring — this becomes the tool description.
- Every tool must have a corresponding benchmark and at least 5 eval cases.
- Servers run on stdio transport for local use, SSE for deployed use.

## When Unsure

Ask for clarification rather than assuming. State your assumptions explicitly
before implementing.
HEREDOC

echo "  Done."
echo ""

# ── 2. Merge MCP servers into ~/.claude/settings.json ───────────────────────
echo "--- Merging MCP server config into $GLOBAL_SETTINGS ---"

FRAGMENT="$REPO_PATH/install/settings-fragment.json"

# Substitute the repo path into the fragment
RESOLVED_FRAGMENT=$(sed "s|{{REPO_PATH}}|$REPO_PATH|g" "$FRAGMENT")

# Merge into settings.json using Python (always available on macOS)
python3 - << PYEOF
import json, sys

settings_path = "$GLOBAL_SETTINGS"
fragment = json.loads('''$RESOLVED_FRAGMENT''')

try:
    with open(settings_path) as f:
        settings = json.load(f)
except (FileNotFoundError, json.JSONDecodeError):
    settings = {}

# Deep merge: only mcpServers key
settings.setdefault("mcpServers", {})
settings["mcpServers"].update(fragment.get("mcpServers", {}))

with open(settings_path, "w") as f:
    json.dump(settings, f, indent=2)
    f.write("\n")

print(f"  Registered MCP servers: {list(fragment.get('mcpServers', {}).keys())}")
PYEOF

echo ""

# ── 3. Install Python + Node dependencies ───────────────────────────────────
if [ "${SKIP_DEPS:-0}" != "1" ]; then
  echo "--- Installing dependencies ---"

  command -v uv >/dev/null 2>&1 || {
    echo "  [skip] uv not found — install from https://docs.astral.sh/uv/install.sh"
  }
  command -v uv >/dev/null 2>&1 && uv sync --all-packages --quiet && echo "  Python deps installed."

  if [ -f "$REPO_PATH/package.json" ]; then
    command -v pnpm >/dev/null 2>&1 || {
      echo "  [skip] pnpm not found — install with: npm install -g pnpm"
    }
    command -v pnpm >/dev/null 2>&1 && pnpm install --silent && echo "  Node deps installed."
  fi

  # Copy .env if not present
  if [ ! -f "$REPO_PATH/.env" ]; then
    cp "$REPO_PATH/.env.example" "$REPO_PATH/.env"
    echo "  Created .env from .env.example — fill in your API keys."
  fi
  echo ""
fi

# ── 4. Summary ───────────────────────────────────────────────────────────────
echo "=== Install complete ==="
echo ""
echo "  Global context : $GLOBAL_CLAUDE_MD"
echo "  MCP servers    : knowledge-base, code-tools"
echo "  Skills         : python-refactor, write-tests, aws-cdk-construct,"
echo "                   temporal-workflow, mcp-server, langgraph-agent, eval-harness"
echo ""
echo "Next steps:"
echo "  1. Fill in $REPO_PATH/.env with your API keys"
echo "  2. Restart Claude Code for MCP server changes to take effect"
echo "  3. To update after pulling: re-run ./install.sh"
